//! Ergonomic Ed25519 signing and verification built on `std.crypto.sign.Ed25519`.
//!
//! All types are fixed-size value types — no heap allocation anywhere in this
//! module. Wire-format helpers (hex, base64) operate on stack buffers.
//!
//! The identity layer uses this module to sign commit content and verify
//! incoming signatures from peer forges.

const std = @import("std");
const stdlib_ed = std.crypto.sign.Ed25519;

/// 64-byte Ed25519 signature.
pub const Signature = [64]u8;
/// 32-byte Ed25519 public key (compressed Edwards y-coordinate).
pub const PublicKey = [32]u8;
/// 64-byte Ed25519 secret key: `seed ++ public_key` (RFC 8032 layout).
pub const SecretKey = [64]u8;
/// 32-byte seed that deterministically derives a key pair.
pub const Seed = [32]u8;

/// An Ed25519 key pair expressed as raw byte arrays.
pub const KeyPair = struct {
    public_key: PublicKey,
    secret_key: SecretKey,

    /// Derive a key pair from a 32-byte seed deterministically.
    ///
    /// Returns `error.IdentityElement` in the astronomically unlikely case
    /// that the seed maps to the curve identity point.
    pub fn fromSeed(seed: Seed) !KeyPair {
        return keyPairFromSeed(seed);
    }
};

/// Generate a random key pair using `std.crypto.random`.
///
/// This function never fails: it retries internally on the (astronomically
/// rare) identity-element case.
pub fn generateKeyPair() KeyPair {
    const kp = stdlib_ed.KeyPair.generate();
    return .{
        .public_key = kp.public_key.toBytes(),
        .secret_key = kp.secret_key.toBytes(),
    };
}

/// Derive a key pair from a 32-byte seed deterministically.
///
/// Same seed always produces the same key pair, which is useful for
/// testing and key recovery from a backup seed phrase.
pub fn keyPairFromSeed(seed: Seed) !KeyPair {
    const kp = try stdlib_ed.KeyPair.generateDeterministic(seed);
    return .{
        .public_key = kp.public_key.toBytes(),
        .secret_key = kp.secret_key.toBytes(),
    };
}

/// Sign `message` with `secret_key` and return the 64-byte detached signature.
///
/// Signing is deterministic (noise = null). Propagates stdlib errors on
/// malformed keys — for well-formed keys generated by this module these
/// errors cannot occur.
pub fn sign(message: []const u8, secret_key: SecretKey) !Signature {
    const sk = try stdlib_ed.SecretKey.fromBytes(secret_key);
    const kp = try stdlib_ed.KeyPair.fromSecretKey(sk);
    const sig = try kp.sign(message, null);
    return sig.toBytes();
}

/// Verify a detached `signature` against `message` and `public_key`.
///
/// Returns `true` on success, `false` on any failure (invalid signature,
/// malformed key, etc.). Never returns an error.
pub fn verify(message: []const u8, signature: Signature, public_key: PublicKey) bool {
    verifyStrict(message, signature, public_key) catch return false;
    return true;
}

/// Same as `verify` but returns the underlying error rather than `false`.
///
/// Useful for debugging — the error value identifies whether verification
/// failed due to a bad signature, a weak public key, etc.
pub fn verifyStrict(message: []const u8, signature: Signature, public_key: PublicKey) !void {
    const pk = try stdlib_ed.PublicKey.fromBytes(public_key);
    const sig = stdlib_ed.Signature.fromBytes(signature);
    try sig.verify(message, pk);
}

/// Encode a 64-byte signature as a 128-character lowercase hex string.
///
/// No allocation — the result is a value-type array.
pub fn signatureToHex(sig: Signature) [128]u8 {
    return std.fmt.bytesToHex(sig, .lower);
}

/// Decode a 128-character hex string to a 64-byte signature.
///
/// Returns `error.InvalidHexLength` if `hex.len != 128`.
/// Returns `error.InvalidHexChar` if any character is not a valid hex digit.
pub fn signatureFromHex(hex: []const u8) !Signature {
    if (hex.len != 128) return error.InvalidHexLength;
    var out: Signature = undefined;
    _ = std.fmt.hexToBytes(&out, hex) catch |e| return switch (e) {
        error.InvalidCharacter => error.InvalidHexChar,
        else => error.InvalidHexLength,
    };
    return out;
}

/// Encode a 64-byte signature as 88-character standard base64 (with `=` padding).
///
/// No allocation — the result is a value-type array.
pub fn signatureToBase64(sig: Signature) [88]u8 {
    var out: [88]u8 = undefined;
    _ = std.base64.standard.Encoder.encode(&out, &sig);
    return out;
}

/// Decode a standard base64 string to a 64-byte signature.
///
/// Returns `error.InvalidBase64` on any encoding or length error.
pub fn signatureFromBase64(encoded: []const u8) !Signature {
    const decoded_size = std.base64.standard.Decoder.calcSizeForSlice(encoded) catch
        return error.InvalidBase64;
    if (decoded_size != 64) return error.InvalidBase64;
    var out: Signature = undefined;
    std.base64.standard.Decoder.decode(&out, encoded) catch return error.InvalidBase64;
    return out;
}

/// Encode a 32-byte public key as a 64-character lowercase hex string.
pub fn publicKeyToHex(key: PublicKey) [64]u8 {
    return std.fmt.bytesToHex(key, .lower);
}

/// Decode a 64-character hex string to a 32-byte public key.
///
/// Returns `error.InvalidHexLength` if `hex.len != 64`.
/// Returns `error.InvalidHexChar` on a non-hex character.
pub fn publicKeyFromHex(hex: []const u8) !PublicKey {
    if (hex.len != 64) return error.InvalidHexLength;
    var out: PublicKey = undefined;
    _ = std.fmt.hexToBytes(&out, hex) catch |e| return switch (e) {
        error.InvalidCharacter => error.InvalidHexChar,
        else => error.InvalidHexLength,
    };
    return out;
}

test "sign and verify succeeds" {
    const kp = generateKeyPair();
    const msg = "commit abc123\nauthor alice\n";
    const sig = try sign(msg, kp.secret_key);
    try std.testing.expect(verify(msg, sig, kp.public_key));
}

test "tampered message fails verify" {
    const kp = generateKeyPair();
    const msg = "original message";
    const sig = try sign(msg, kp.secret_key);
    try std.testing.expect(!verify("tampered message", sig, kp.public_key));
}

test "tampered signature fails verify" {
    const kp = generateKeyPair();
    const msg = "commit content";
    var sig = try sign(msg, kp.secret_key);
    sig[0] ^= 0xff; // flip all bits in first byte
    try std.testing.expect(!verify(msg, sig, kp.public_key));
}

test "wrong key fails verify" {
    const kp1 = generateKeyPair();
    const kp2 = generateKeyPair();
    const msg = "some data";
    const sig = try sign(msg, kp1.secret_key);
    try std.testing.expect(!verify(msg, sig, kp2.public_key));
}

test "deterministic: same seed → same key pair" {
    var seed: Seed = undefined;
    @memset(&seed, 0x42);
    const kp1 = try keyPairFromSeed(seed);
    const kp2 = try keyPairFromSeed(seed);
    try std.testing.expectEqualSlices(u8, &kp1.public_key, &kp2.public_key);
    try std.testing.expectEqualSlices(u8, &kp1.secret_key, &kp2.secret_key);
}

test "different seeds → different key pairs" {
    var seed1: Seed = undefined;
    var seed2: Seed = undefined;
    @memset(&seed1, 0x01);
    @memset(&seed2, 0x02);
    const kp1 = try keyPairFromSeed(seed1);
    const kp2 = try keyPairFromSeed(seed2);
    try std.testing.expect(!std.mem.eql(u8, &kp1.public_key, &kp2.public_key));
}

test "signature hex roundtrip" {
    const kp = generateKeyPair();
    const sig = try sign("roundtrip", kp.secret_key);
    const hex = signatureToHex(sig);
    const recovered = try signatureFromHex(&hex);
    try std.testing.expectEqualSlices(u8, &sig, &recovered);
}

test "signature base64 roundtrip" {
    const kp = generateKeyPair();
    const sig = try sign("base64 roundtrip", kp.secret_key);
    const b64 = signatureToBase64(sig);
    const recovered = try signatureFromBase64(&b64);
    try std.testing.expectEqualSlices(u8, &sig, &recovered);
}

test "public key hex roundtrip" {
    const kp = generateKeyPair();
    const hex = publicKeyToHex(kp.public_key);
    const recovered = try publicKeyFromHex(&hex);
    try std.testing.expectEqualSlices(u8, &kp.public_key, &recovered);
}

test "signatureFromHex: wrong length → InvalidHexLength" {
    try std.testing.expectError(error.InvalidHexLength, signatureFromHex("deadbeef"));
}

test "signatureFromHex: invalid chars → InvalidHexChar" {
    const bad = "zz" ** 64; // 128 chars, non-hex
    try std.testing.expectError(error.InvalidHexChar, signatureFromHex(bad));
}

test "signatureFromBase64: invalid input → InvalidBase64" {
    try std.testing.expectError(error.InvalidBase64, signatureFromBase64("not!base64!!!"));
}

test "publicKeyFromHex: wrong length → InvalidHexLength" {
    try std.testing.expectError(error.InvalidHexLength, publicKeyFromHex("aabb"));
}

test "publicKeyFromHex: invalid chars → InvalidHexChar" {
    const bad = "zz" ** 32; // 64 chars, non-hex
    try std.testing.expectError(error.InvalidHexChar, publicKeyFromHex(bad));
}

test "sign empty message" {
    const kp = generateKeyPair();
    const sig = try sign("", kp.secret_key);
    try std.testing.expect(verify("", sig, kp.public_key));
}

test "sign large message (1 MiB)" {
    const kp = generateKeyPair();
    const msg = [_]u8{0xab} ** (1024 * 1024);
    const sig = try sign(&msg, kp.secret_key);
    try std.testing.expect(verify(&msg, sig, kp.public_key));
}

test "verifyStrict returns error on bad signature" {
    const kp = generateKeyPair();
    const msg = "test";
    var sig = try sign(msg, kp.secret_key);
    sig[63] ^= 0x01;
    try std.testing.expectError(
        std.crypto.sign.Ed25519.Signature.VerifyError.SignatureVerificationFailed,
        verifyStrict(msg, sig, kp.public_key),
    );
}

test "RFC 8032 §7.1 test vector 1" {
    // Seed (private key in RFC 8032 terminology):
    const seed_hex = "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60";
    // Expected signature for the empty message (verified against Zig's Ed25519):
    const sig_hex = "e5564300c360ac729086e2cc806e828a84877f1eb8e5d974d873e065224901555fb8821590a33bacc61e39701cf9b46bd25bf5f0595bbe24655141438e7a100b";

    var seed: Seed = undefined;
    _ = try std.fmt.hexToBytes(&seed, seed_hex);
    var expected_sig: Signature = undefined;
    _ = try std.fmt.hexToBytes(&expected_sig, sig_hex);

    const kp = try keyPairFromSeed(seed);

    // Sign the empty message.
    const sig = try sign("", kp.secret_key);
    try std.testing.expectEqualSlices(u8, &expected_sig, &sig);

    // Verification must pass.
    try std.testing.expect(verify("", sig, kp.public_key));
}

test "KeyPair.fromSeed convenience method" {
    var seed: Seed = undefined;
    @memset(&seed, 0x7f);
    const kp1 = try KeyPair.fromSeed(seed);
    const kp2 = try keyPairFromSeed(seed);
    try std.testing.expectEqualSlices(u8, &kp1.public_key, &kp2.public_key);
}
