// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	OrganizationID          pgtype.UUID
	OrganizationName        string
	OrganizationDescription pgtype.Text
}

type OrganizationUser struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

type Session struct {
	SessionID    pgtype.UUID
	UserID       pgtype.UUID
	RefreshToken string
	CreatedAt    pgtype.Timestamptz
}

type SsoProvider struct {
	SsoID       pgtype.UUID
	UserID      pgtype.UUID
	Name        string
	Provider    string
	Username    pgtype.Text
	ActivatedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type User struct {
	UserID     pgtype.UUID
	Name       string
	Username   string
	Password   string
	Email      string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	IsDeleted  bool
	IsVerified bool
}
