// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToOrganization = `-- name: AddUserToOrganization :exec
INSERT INTO organization_users (organization_id, user_id)
VALUES ($1, $2)
`

type AddUserToOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) AddUserToOrganization(ctx context.Context, arg AddUserToOrganizationParams) error {
	_, err := q.db.Exec(ctx, addUserToOrganization, arg.OrganizationID, arg.UserID)
	return err
}

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (organization_id, organization_name, organization_description)
VALUES ($1, $2, $3)
RETURNING organization_id, organization_name, organization_description
`

type CreateOrganizationParams struct {
	OrganizationID          pgtype.UUID
	OrganizationName        string
	OrganizationDescription pgtype.Text
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.OrganizationID, arg.OrganizationName, arg.OrganizationDescription)
	var i Organization
	err := row.Scan(&i.OrganizationID, &i.OrganizationName, &i.OrganizationDescription)
	return i, err
}

const deleteOrganizationByID = `-- name: DeleteOrganizationByID :exec
DELETE FROM organizations
WHERE organization_id = $1
`

func (q *Queries) DeleteOrganizationByID(ctx context.Context, organizationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationByID, organizationID)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT organization_id, organization_name, organization_description FROM organizations
WHERE organization_id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, organizationID pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, organizationID)
	var i Organization
	err := row.Scan(&i.OrganizationID, &i.OrganizationName, &i.OrganizationDescription)
	return i, err
}

const getOrganizationsByUserID = `-- name: GetOrganizationsByUserID :many
SELECT o.organization_id, o.organization_name, o.organization_description FROM organizations o
JOIN organization_users ou ON o.organization_id = ou.organization_id
WHERE ou.user_id = $1
`

func (q *Queries) GetOrganizationsByUserID(ctx context.Context, userID pgtype.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getOrganizationsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Organization
	for rows.Next() {
		var i Organization
		if err := rows.Scan(&i.OrganizationID, &i.OrganizationName, &i.OrganizationDescription); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrganizationID = `-- name: GetUsersByOrganizationID :many
SELECT u.user_id, u.name, u.username, u.password, u.email, u.created_at, u.updated_at, u.deleted_at, u.is_deleted, u.is_verified FROM users u
JOIN organization_users ou ON u.user_id = ou.user_id
WHERE ou.organization_id = $1 AND u.is_deleted = FALSE
`

func (q *Queries) GetUsersByOrganizationID(ctx context.Context, organizationID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByOrganizationID, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsDeleted,
			&i.IsVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromOrganization = `-- name: RemoveUserFromOrganization :exec
DELETE FROM organization_users
WHERE organization_id = $1 AND user_id = $2
`

type RemoveUserFromOrganizationParams struct {
	OrganizationID pgtype.UUID
	UserID         pgtype.UUID
}

func (q *Queries) RemoveUserFromOrganization(ctx context.Context, arg RemoveUserFromOrganizationParams) error {
	_, err := q.db.Exec(ctx, removeUserFromOrganization, arg.OrganizationID, arg.UserID)
	return err
}
