// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repository.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO git_repository (id, name, description, is_private, owner_id, default_ref, is_deleted, head, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, false, '', now(), now())
RETURNING id, name, description, is_private, is_deleted, created_at, updated_at, owner_id, default_ref, head
`

type CreateRepositoryParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	IsPrivate   bool
	OwnerID     pgtype.UUID
	DefaultRef  string
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (GitRepository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPrivate,
		arg.OwnerID,
		arg.DefaultRef,
	)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.DefaultRef,
		&i.Head,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, name, description, is_private, is_deleted, created_at, updated_at, owner_id, default_ref, head FROM git_repository WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id pgtype.UUID) (GitRepository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.DefaultRef,
		&i.Head,
	)
	return i, err
}

const getRepositoryByOwnerId = `-- name: GetRepositoryByOwnerId :many
SELECT id, name, description, is_private, is_deleted, created_at, updated_at, owner_id, default_ref, head FROM git_repository WHERE owner_id = $1
`

func (q *Queries) GetRepositoryByOwnerId(ctx context.Context, ownerID pgtype.UUID) ([]GitRepository, error) {
	rows, err := q.db.Query(ctx, getRepositoryByOwnerId, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitRepository
	for rows.Next() {
		var i GitRepository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.DefaultRef,
			&i.Head,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepositoryByRepositoryName = `-- name: GetRepositoryByRepositoryName :many
SELECT id, name, description, is_private, is_deleted, created_at, updated_at, owner_id, default_ref, head FROM git_repository WHERE name = $1
`

func (q *Queries) GetRepositoryByRepositoryName(ctx context.Context, name string) ([]GitRepository, error) {
	rows, err := q.db.Query(ctx, getRepositoryByRepositoryName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GitRepository
	for rows.Next() {
		var i GitRepository
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.IsPrivate,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerID,
			&i.DefaultRef,
			&i.Head,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRepository = `-- name: SoftDeleteRepository :one
UPDATE git_repository
SET is_deleted = true, updated_at = now()
WHERE id = $1
RETURNING id, name, description, is_private, is_deleted, created_at, updated_at, owner_id, default_ref, head
`

func (q *Queries) SoftDeleteRepository(ctx context.Context, id pgtype.UUID) (GitRepository, error) {
	row := q.db.QueryRow(ctx, softDeleteRepository, id)
	var i GitRepository
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.IsPrivate,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerID,
		&i.DefaultRef,
		&i.Head,
	)
	return i, err
}

const updateRepository = `-- name: UpdateRepository :exec
UPDATE git_repository
SET updated_at= now(), name= $2, description= $3, is_private= $4, owner_id= $5, default_ref= $6
WHERE id= $1
`

type UpdateRepositoryParams struct {
	ID          pgtype.UUID
	Name        string
	Description pgtype.Text
	IsPrivate   bool
	OwnerID     pgtype.UUID
	DefaultRef  string
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error {
	_, err := q.db.Exec(ctx, updateRepository,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsPrivate,
		arg.OwnerID,
		arg.DefaultRef,
	)
	return err
}
