// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSSO = `-- name: CreateSSO :one
INSERT INTO sso_providers (sso_id, user_id, name, provider, username, activated_at, created_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING sso_id, user_id, name, provider, username, activated_at, created_at
`

type CreateSSOParams struct {
	SsoID    pgtype.UUID
	UserID   pgtype.UUID
	Name     string
	Provider string
	Username pgtype.Text
}

func (q *Queries) CreateSSO(ctx context.Context, arg CreateSSOParams) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, createSSO,
		arg.SsoID,
		arg.UserID,
		arg.Name,
		arg.Provider,
		arg.Username,
	)
	var i SsoProvider
	err := row.Scan(
		&i.SsoID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Username,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSSO = `-- name: DeleteSSO :exec
DELETE FROM sso_providers
WHERE sso_id = $1
`

func (q *Queries) DeleteSSO(ctx context.Context, ssoID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSO, ssoID)
	return err
}

const getSSOByProviderAndUsername = `-- name: GetSSOByProviderAndUsername :one
SELECT sso_id, user_id, name, provider, username, activated_at, created_at FROM sso_providers
WHERE provider = $1 AND username = $2
`

type GetSSOByProviderAndUsernameParams struct {
	Provider string
	Username pgtype.Text
}

func (q *Queries) GetSSOByProviderAndUsername(ctx context.Context, arg GetSSOByProviderAndUsernameParams) (SsoProvider, error) {
	row := q.db.QueryRow(ctx, getSSOByProviderAndUsername, arg.Provider, arg.Username)
	var i SsoProvider
	err := row.Scan(
		&i.SsoID,
		&i.UserID,
		&i.Name,
		&i.Provider,
		&i.Username,
		&i.ActivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSSOByUserID = `-- name: GetSSOByUserID :many
SELECT sso_id, user_id, name, provider, username, activated_at, created_at FROM sso_providers
WHERE user_id = $1
`

func (q *Queries) GetSSOByUserID(ctx context.Context, userID pgtype.UUID) ([]SsoProvider, error) {
	rows, err := q.db.Query(ctx, getSSOByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SsoProvider
	for rows.Next() {
		var i SsoProvider
		if err := rows.Scan(
			&i.SsoID,
			&i.UserID,
			&i.Name,
			&i.Provider,
			&i.Username,
			&i.ActivatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
